controller_manager:
  ros__parameters:
    update_rate: 30

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    shooter_position_controller:
      type: position_controllers/JointGroupPositionController

    shooter_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    intake_position_controller:
      type: position_controllers/JointGroupPositionController

    intake_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    stick_position_controller:
      type: position_controllers/JointGroupPositionController


diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['FL_wheel_joint', 'BL_wheel_joint']
    right_wheel_names: ['FR_wheel_joint', 'BR_wheel_joint']
    wheel_separation: 0.297
    wheel_radius: 0.033

    use_stamped_vel: false
    # TODO I think there's a param that can be set such that it doesn't expect
    #      encoder values back

shooter_position_controller:
  ros__parameters:
    joints: ['yaw_shooter_servo_joint', 'pitch_shooter_servo_joint']

shooter_velocity_controller:
  ros__parameters:
    joints: ['left_shooter_wheel_joint', 'right_shooter_wheel_joint']

intake_position_controller:
  ros__parameters:
    joints: ['yaw_shooter_servo_joint', 'pitch_shooter_servo_joint']

intake_velocity_controller:
  ros__parameters:
    joints: ['left_shooter_wheel_joint', 'right_shooter_wheel_joint']

stick_position_controller:
  ros__parameters:
    joints: ['yaw_shooter_servo_joint', 'pitch_shooter_servo_joint']
