controller_manager:
  ros__parameters:
    update_rate: 30

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['FL_wheel_joint', 'BL_wheel_joint']
    right_wheel_names: ['FR_wheel_joint', 'BR_wheel_joint']
    wheel_separation: 0.297
    wheel_radius: 0.033

    use_stamped_vel: false

position_controller:
  ros__parameters:
    joints: ['yaw_shooter_servo_joint', 'pitch_shooter_servo_joint']

velocity_controller:
  ros__parameters:
    joints: ['left_shooter_wheel_joint', 'right_shooter_wheel_joint']

