controller_manager:
  ros__parameters:
    update_rate: 30

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    shooter_position_controller:
      type: position_controllers/JointGroupPositionController

    shooter_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    intake_position_controller:
      type: position_controllers/JointGroupPositionController

    intake_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    shooter_indexer_controller:
      type: velocity_controllers/JointGroupPositionController


mecanum_controller:
  ros__parameters:
    reference_timeout: 0.0

    front_left_wheel_command_joint_name: "FL_wheel_joint"
    front_right_wheel_command_joint_name: "FR_wheel_joint"
    rear_right_wheel_command_joint_name: "BR_wheel_joint"
    rear_left_wheel_command_joint_name: "BL_wheel_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.03537
      sum_of_robot_center_projection_on_X_Y_axis: 0.236

    enable_odom_tf: false
    use_stamped_vel: false

shooter_position_controller:
  ros__parameters:
    joints: ['yaw_shooter_servo_joint', 'pitch_shooter_servo_joint']

shooter_velocity_controller:
  ros__parameters:
    joints: ['left_shooter_wheel_joint', 'right_shooter_wheel_joint']

intake_position_controller:
  ros__parameters:
    joints: ['intake_servo_joint']

intake_velocity_controller:
  ros__parameters:
    joints: ['intake_pulley_joint']

shooter_indexer_controller:
  ros__parameters:
    joints: ['shooter_indexer_joint']
