twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: nav_vel
        timeout: 0.5
        priority: 99
      joystick:
        topic: joy_vel
        timeout: 0.5
        priority: 100
